# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Video(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, photo_urls: List[str]=None, age: float=None):  # noqa: E501
        """Video - a model defined in Swagger

        :param id: The id of this Video.  # noqa: E501
        :type id: int
        :param name: The name of this Video.  # noqa: E501
        :type name: str
        :param photo_urls: The photo_urls of this Video.  # noqa: E501
        :type photo_urls: List[str]
        :param age: The age of this Video.  # noqa: E501
        :type age: float
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'photo_urls': List[str],
            'age': float
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'photo_urls': 'photoUrls',
            'age': 'age'
        }

        self._id = id
        self._name = name
        self._photo_urls = photo_urls
        self._age = age

    @classmethod
    def from_dict(cls, dikt) -> 'Video':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Video of this Video.  # noqa: E501
        :rtype: Video
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Video.


        :return: The id of this Video.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Video.


        :param id: The id of this Video.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Video.


        :return: The name of this Video.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Video.


        :param name: The name of this Video.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def photo_urls(self) -> List[str]:
        """Gets the photo_urls of this Video.


        :return: The photo_urls of this Video.
        :rtype: List[str]
        """
        return self._photo_urls

    @photo_urls.setter
    def photo_urls(self, photo_urls: List[str]):
        """Sets the photo_urls of this Video.


        :param photo_urls: The photo_urls of this Video.
        :type photo_urls: List[str]
        """
        if photo_urls is None:
            raise ValueError("Invalid value for `photo_urls`, must not be `None`")  # noqa: E501

        self._photo_urls = photo_urls

    @property
    def age(self) -> float:
        """Gets the age of this Video.

        age minimum to watch the video  # noqa: E501

        :return: The age of this Video.
        :rtype: float
        """
        return self._age

    @age.setter
    def age(self, age: float):
        """Sets the age of this Video.

        age minimum to watch the video  # noqa: E501

        :param age: The age of this Video.
        :type age: float
        """

        self._age = age
